import {
  siTypescript,
  siGo,
  siPython,
  siJavascript,
  siReact,
  siNextdotjs,
  siNodedotjs,
  siDocker,
  siPostgresql,
  siMongodb,
  siGit,
  siGraphql,
  siNetlify,
  siHtml5,
  siCss,
  siNestjs,
  siSass,
  siSocketdotio,
  siVuedotjs,
  siPnpm,
  siNpm,
  siSvelte,
  siCypress,
  siGithubactions,
  siGooglecloud,
  type SimpleIcon,
} from "simple-icons"

const iconMap: Record<string, SimpleIcon> = {
  TypeScript: siTypescript,
  Go: siGo,
  Python: siPython,
  JavaScript: siJavascript,
  React: siReact,
  "Next.js": siNextdotjs,
  "Node.js": siNodedotjs,
  Docker: siDocker,
  PostgreSQL: siPostgresql,
  MongoDB: siMongodb,
  Git: siGit,
  GraphQL: siGraphql,
  Netlify: siNetlify,
  HTML5: siHtml5,
  CSS3: siCss,
  "Nest.js": siNestjs,
  SASS: siSass,
  "Socket.io": siSocketdotio,
  Vue: siVuedotjs,
  Pnpm: siPnpm,
  Npm: siNpm,
  SvelteKit: siSvelte,
  Cypress: siCypress,
  "CI/CD": siGithubactions,
  "Cloud Infrastructure": siGooglecloud,
}

export function getTechIcon(name: string): SimpleIcon | null {
  return iconMap[name] ?? null
}
